/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClientRouteImport } from './routes/client'
import { Route as BarberRouteImport } from './routes/barber'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ClientIndexRouteImport } from './routes/client.index'
import { Route as BarberIndexRouteImport } from './routes/barber.index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardQueueRouteImport } from './routes/dashboard.queue'
import { Route as DashboardPosRouteImport } from './routes/dashboard.pos'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard.calendar'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as ClientStyleStudioRouteImport } from './routes/client.style-studio'
import { Route as ClientProfileRouteImport } from './routes/client.profile'
import { Route as BarberQueueRouteImport } from './routes/barber.queue'
import { Route as BarberProfileRouteImport } from './routes/barber.profile'
import { Route as BarberEarningsRouteImport } from './routes/barber.earnings'
import { Route as DashboardClientsIndexRouteImport } from './routes/dashboard.clients.index'
import { Route as DashboardBarbersIndexRouteImport } from './routes/dashboard.barbers.index'
import { Route as ClientBarbersIndexRouteImport } from './routes/client.barbers.index'
import { Route as DashboardClientsIdRouteImport } from './routes/dashboard.clients.$id'
import { Route as DashboardBarbersIdRouteImport } from './routes/dashboard.barbers.$id'
import { Route as ClientSurveyIdRouteImport } from './routes/client.survey.$id'
import { Route as ClientQueueIdRouteImport } from './routes/client.queue.$id'
import { Route as ClientBarbersIdRouteImport } from './routes/client.barbers.$id'
import { Route as ApiStyleStudioTryonRouteImport } from './routes/api.style-studio.tryon'
import { Route as ApiStyleStudioDiscoverRouteImport } from './routes/api.style-studio.discover'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const BarberRoute = BarberRouteImport.update({
  id: '/barber',
  path: '/barber',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const BarberIndexRoute = BarberIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BarberRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQueueRoute = DashboardQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPosRoute = DashboardPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const ClientStyleStudioRoute = ClientStyleStudioRouteImport.update({
  id: '/style-studio',
  path: '/style-studio',
  getParentRoute: () => ClientRoute,
} as any)
const ClientProfileRoute = ClientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ClientRoute,
} as any)
const BarberQueueRoute = BarberQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => BarberRoute,
} as any)
const BarberProfileRoute = BarberProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => BarberRoute,
} as any)
const BarberEarningsRoute = BarberEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => BarberRoute,
} as any)
const DashboardClientsIndexRoute = DashboardClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBarbersIndexRoute = DashboardBarbersIndexRouteImport.update({
  id: '/barbers/',
  path: '/barbers/',
  getParentRoute: () => DashboardRoute,
} as any)
const ClientBarbersIndexRoute = ClientBarbersIndexRouteImport.update({
  id: '/barbers/',
  path: '/barbers/',
  getParentRoute: () => ClientRoute,
} as any)
const DashboardClientsIdRoute = DashboardClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBarbersIdRoute = DashboardBarbersIdRouteImport.update({
  id: '/barbers/$id',
  path: '/barbers/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const ClientSurveyIdRoute = ClientSurveyIdRouteImport.update({
  id: '/survey/$id',
  path: '/survey/$id',
  getParentRoute: () => ClientRoute,
} as any)
const ClientQueueIdRoute = ClientQueueIdRouteImport.update({
  id: '/queue/$id',
  path: '/queue/$id',
  getParentRoute: () => ClientRoute,
} as any)
const ClientBarbersIdRoute = ClientBarbersIdRouteImport.update({
  id: '/barbers/$id',
  path: '/barbers/$id',
  getParentRoute: () => ClientRoute,
} as any)
const ApiStyleStudioTryonRoute = ApiStyleStudioTryonRouteImport.update({
  id: '/api/style-studio/tryon',
  path: '/api/style-studio/tryon',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStyleStudioDiscoverRoute = ApiStyleStudioDiscoverRouteImport.update({
  id: '/api/style-studio/discover',
  path: '/api/style-studio/discover',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/barber': typeof BarberRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/barber/earnings': typeof BarberEarningsRoute
  '/barber/profile': typeof BarberProfileRoute
  '/barber/queue': typeof BarberQueueRoute
  '/client/profile': typeof ClientProfileRoute
  '/client/style-studio': typeof ClientStyleStudioRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/pos': typeof DashboardPosRoute
  '/dashboard/queue': typeof DashboardQueueRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/barber/': typeof BarberIndexRoute
  '/client/': typeof ClientIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/style-studio/discover': typeof ApiStyleStudioDiscoverRoute
  '/api/style-studio/tryon': typeof ApiStyleStudioTryonRoute
  '/client/barbers/$id': typeof ClientBarbersIdRoute
  '/client/queue/$id': typeof ClientQueueIdRoute
  '/client/survey/$id': typeof ClientSurveyIdRoute
  '/dashboard/barbers/$id': typeof DashboardBarbersIdRoute
  '/dashboard/clients/$id': typeof DashboardClientsIdRoute
  '/client/barbers/': typeof ClientBarbersIndexRoute
  '/dashboard/barbers/': typeof DashboardBarbersIndexRoute
  '/dashboard/clients/': typeof DashboardClientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/barber/earnings': typeof BarberEarningsRoute
  '/barber/profile': typeof BarberProfileRoute
  '/barber/queue': typeof BarberQueueRoute
  '/client/profile': typeof ClientProfileRoute
  '/client/style-studio': typeof ClientStyleStudioRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/pos': typeof DashboardPosRoute
  '/dashboard/queue': typeof DashboardQueueRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/barber': typeof BarberIndexRoute
  '/client': typeof ClientIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/style-studio/discover': typeof ApiStyleStudioDiscoverRoute
  '/api/style-studio/tryon': typeof ApiStyleStudioTryonRoute
  '/client/barbers/$id': typeof ClientBarbersIdRoute
  '/client/queue/$id': typeof ClientQueueIdRoute
  '/client/survey/$id': typeof ClientSurveyIdRoute
  '/dashboard/barbers/$id': typeof DashboardBarbersIdRoute
  '/dashboard/clients/$id': typeof DashboardClientsIdRoute
  '/client/barbers': typeof ClientBarbersIndexRoute
  '/dashboard/barbers': typeof DashboardBarbersIndexRoute
  '/dashboard/clients': typeof DashboardClientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/barber': typeof BarberRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/barber/earnings': typeof BarberEarningsRoute
  '/barber/profile': typeof BarberProfileRoute
  '/barber/queue': typeof BarberQueueRoute
  '/client/profile': typeof ClientProfileRoute
  '/client/style-studio': typeof ClientStyleStudioRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/pos': typeof DashboardPosRoute
  '/dashboard/queue': typeof DashboardQueueRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/barber/': typeof BarberIndexRoute
  '/client/': typeof ClientIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/style-studio/discover': typeof ApiStyleStudioDiscoverRoute
  '/api/style-studio/tryon': typeof ApiStyleStudioTryonRoute
  '/client/barbers/$id': typeof ClientBarbersIdRoute
  '/client/queue/$id': typeof ClientQueueIdRoute
  '/client/survey/$id': typeof ClientSurveyIdRoute
  '/dashboard/barbers/$id': typeof DashboardBarbersIdRoute
  '/dashboard/clients/$id': typeof DashboardClientsIdRoute
  '/client/barbers/': typeof ClientBarbersIndexRoute
  '/dashboard/barbers/': typeof DashboardBarbersIndexRoute
  '/dashboard/clients/': typeof DashboardClientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/barber'
    | '/client'
    | '/dashboard'
    | '/barber/earnings'
    | '/barber/profile'
    | '/barber/queue'
    | '/client/profile'
    | '/client/style-studio'
    | '/dashboard/analytics'
    | '/dashboard/calendar'
    | '/dashboard/pos'
    | '/dashboard/queue'
    | '/dashboard/settings'
    | '/barber/'
    | '/client/'
    | '/dashboard/'
    | '/api/style-studio/discover'
    | '/api/style-studio/tryon'
    | '/client/barbers/$id'
    | '/client/queue/$id'
    | '/client/survey/$id'
    | '/dashboard/barbers/$id'
    | '/dashboard/clients/$id'
    | '/client/barbers/'
    | '/dashboard/barbers/'
    | '/dashboard/clients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/barber/earnings'
    | '/barber/profile'
    | '/barber/queue'
    | '/client/profile'
    | '/client/style-studio'
    | '/dashboard/analytics'
    | '/dashboard/calendar'
    | '/dashboard/pos'
    | '/dashboard/queue'
    | '/dashboard/settings'
    | '/barber'
    | '/client'
    | '/dashboard'
    | '/api/style-studio/discover'
    | '/api/style-studio/tryon'
    | '/client/barbers/$id'
    | '/client/queue/$id'
    | '/client/survey/$id'
    | '/dashboard/barbers/$id'
    | '/dashboard/clients/$id'
    | '/client/barbers'
    | '/dashboard/barbers'
    | '/dashboard/clients'
  id:
    | '__root__'
    | '/'
    | '/barber'
    | '/client'
    | '/dashboard'
    | '/barber/earnings'
    | '/barber/profile'
    | '/barber/queue'
    | '/client/profile'
    | '/client/style-studio'
    | '/dashboard/analytics'
    | '/dashboard/calendar'
    | '/dashboard/pos'
    | '/dashboard/queue'
    | '/dashboard/settings'
    | '/barber/'
    | '/client/'
    | '/dashboard/'
    | '/api/style-studio/discover'
    | '/api/style-studio/tryon'
    | '/client/barbers/$id'
    | '/client/queue/$id'
    | '/client/survey/$id'
    | '/dashboard/barbers/$id'
    | '/dashboard/clients/$id'
    | '/client/barbers/'
    | '/dashboard/barbers/'
    | '/dashboard/clients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BarberRoute: typeof BarberRouteWithChildren
  ClientRoute: typeof ClientRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  ApiStyleStudioDiscoverRoute: typeof ApiStyleStudioDiscoverRoute
  ApiStyleStudioTryonRoute: typeof ApiStyleStudioTryonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barber': {
      id: '/barber'
      path: '/barber'
      fullPath: '/barber'
      preLoaderRoute: typeof BarberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/client/': {
      id: '/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/barber/': {
      id: '/barber/'
      path: '/'
      fullPath: '/barber/'
      preLoaderRoute: typeof BarberIndexRouteImport
      parentRoute: typeof BarberRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/queue': {
      id: '/dashboard/queue'
      path: '/queue'
      fullPath: '/dashboard/queue'
      preLoaderRoute: typeof DashboardQueueRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pos': {
      id: '/dashboard/pos'
      path: '/pos'
      fullPath: '/dashboard/pos'
      preLoaderRoute: typeof DashboardPosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/client/style-studio': {
      id: '/client/style-studio'
      path: '/style-studio'
      fullPath: '/client/style-studio'
      preLoaderRoute: typeof ClientStyleStudioRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/profile': {
      id: '/client/profile'
      path: '/profile'
      fullPath: '/client/profile'
      preLoaderRoute: typeof ClientProfileRouteImport
      parentRoute: typeof ClientRoute
    }
    '/barber/queue': {
      id: '/barber/queue'
      path: '/queue'
      fullPath: '/barber/queue'
      preLoaderRoute: typeof BarberQueueRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/profile': {
      id: '/barber/profile'
      path: '/profile'
      fullPath: '/barber/profile'
      preLoaderRoute: typeof BarberProfileRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/earnings': {
      id: '/barber/earnings'
      path: '/earnings'
      fullPath: '/barber/earnings'
      preLoaderRoute: typeof BarberEarningsRouteImport
      parentRoute: typeof BarberRoute
    }
    '/dashboard/clients/': {
      id: '/dashboard/clients/'
      path: '/clients'
      fullPath: '/dashboard/clients/'
      preLoaderRoute: typeof DashboardClientsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/barbers/': {
      id: '/dashboard/barbers/'
      path: '/barbers'
      fullPath: '/dashboard/barbers/'
      preLoaderRoute: typeof DashboardBarbersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/client/barbers/': {
      id: '/client/barbers/'
      path: '/barbers'
      fullPath: '/client/barbers/'
      preLoaderRoute: typeof ClientBarbersIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/dashboard/clients/$id': {
      id: '/dashboard/clients/$id'
      path: '/clients/$id'
      fullPath: '/dashboard/clients/$id'
      preLoaderRoute: typeof DashboardClientsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/barbers/$id': {
      id: '/dashboard/barbers/$id'
      path: '/barbers/$id'
      fullPath: '/dashboard/barbers/$id'
      preLoaderRoute: typeof DashboardBarbersIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/client/survey/$id': {
      id: '/client/survey/$id'
      path: '/survey/$id'
      fullPath: '/client/survey/$id'
      preLoaderRoute: typeof ClientSurveyIdRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/queue/$id': {
      id: '/client/queue/$id'
      path: '/queue/$id'
      fullPath: '/client/queue/$id'
      preLoaderRoute: typeof ClientQueueIdRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/barbers/$id': {
      id: '/client/barbers/$id'
      path: '/barbers/$id'
      fullPath: '/client/barbers/$id'
      preLoaderRoute: typeof ClientBarbersIdRouteImport
      parentRoute: typeof ClientRoute
    }
    '/api/style-studio/tryon': {
      id: '/api/style-studio/tryon'
      path: '/api/style-studio/tryon'
      fullPath: '/api/style-studio/tryon'
      preLoaderRoute: typeof ApiStyleStudioTryonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/style-studio/discover': {
      id: '/api/style-studio/discover'
      path: '/api/style-studio/discover'
      fullPath: '/api/style-studio/discover'
      preLoaderRoute: typeof ApiStyleStudioDiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BarberRouteChildren {
  BarberEarningsRoute: typeof BarberEarningsRoute
  BarberProfileRoute: typeof BarberProfileRoute
  BarberQueueRoute: typeof BarberQueueRoute
  BarberIndexRoute: typeof BarberIndexRoute
}

const BarberRouteChildren: BarberRouteChildren = {
  BarberEarningsRoute: BarberEarningsRoute,
  BarberProfileRoute: BarberProfileRoute,
  BarberQueueRoute: BarberQueueRoute,
  BarberIndexRoute: BarberIndexRoute,
}

const BarberRouteWithChildren =
  BarberRoute._addFileChildren(BarberRouteChildren)

interface ClientRouteChildren {
  ClientProfileRoute: typeof ClientProfileRoute
  ClientStyleStudioRoute: typeof ClientStyleStudioRoute
  ClientIndexRoute: typeof ClientIndexRoute
  ClientBarbersIdRoute: typeof ClientBarbersIdRoute
  ClientQueueIdRoute: typeof ClientQueueIdRoute
  ClientSurveyIdRoute: typeof ClientSurveyIdRoute
  ClientBarbersIndexRoute: typeof ClientBarbersIndexRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientProfileRoute: ClientProfileRoute,
  ClientStyleStudioRoute: ClientStyleStudioRoute,
  ClientIndexRoute: ClientIndexRoute,
  ClientBarbersIdRoute: ClientBarbersIdRoute,
  ClientQueueIdRoute: ClientQueueIdRoute,
  ClientSurveyIdRoute: ClientSurveyIdRoute,
  ClientBarbersIndexRoute: ClientBarbersIndexRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardPosRoute: typeof DashboardPosRoute
  DashboardQueueRoute: typeof DashboardQueueRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBarbersIdRoute: typeof DashboardBarbersIdRoute
  DashboardClientsIdRoute: typeof DashboardClientsIdRoute
  DashboardBarbersIndexRoute: typeof DashboardBarbersIndexRoute
  DashboardClientsIndexRoute: typeof DashboardClientsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardPosRoute: DashboardPosRoute,
  DashboardQueueRoute: DashboardQueueRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBarbersIdRoute: DashboardBarbersIdRoute,
  DashboardClientsIdRoute: DashboardClientsIdRoute,
  DashboardBarbersIndexRoute: DashboardBarbersIndexRoute,
  DashboardClientsIndexRoute: DashboardClientsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BarberRoute: BarberRouteWithChildren,
  ClientRoute: ClientRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  ApiStyleStudioDiscoverRoute: ApiStyleStudioDiscoverRoute,
  ApiStyleStudioTryonRoute: ApiStyleStudioTryonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
